### ISSUE TITLE
Need help with using this theme in Opera GX web-modding 

### ISSUE THREAD

**Issue by Rekiro** [arv-anshul/Distraction-Free-YT-Stylus#1]
Hello there! I really like this theme. I need a little help with it, though.  I tried using it through the web-modding feature in the Opera GX browser, but I couldn't because the code needed some modifications depending on how Opera inserts CSS into the web pages. Can you please help me with that?

**Comment by arv-anshul** [comment]
Yes I can help you. Although I don't know about **Opera GX browser** but it will be my pleasure.

**Question:**
- Where did you get my theme recommendation?

**Comment by Rekiro** [comment]
Hi! Thanks a lot for replying! 

I found your theme while I was searching for Youtube themes on GitHub. 

Opera GX has a built-in feature called web modding that's similar to the extension Stylus, except that I think it's much lighter than the latter since it's in-built into the browser. 

Also, if you want, you can post your theme on [Opera GX Mod Store](https://store.gx.me).

**Comment by arv-anshul** [comment]
### Hi! 😃 Thanks for replying my question and 👍 considering my theme to use.

I can't see the **CSS** behind the theme. Then how do I know the syntax for it.  
Also, I don't want to upload on many websites. It is better to store on GitHub as it is easy to manage. You can upload (if you want) it on **Opera GX Mod Store** and use it.

**Use my theme CSS and use it on your browser.**

**Comment by Rekiro** [comment]
Okay, I understand. 

But can you please suggest another lightweight CSS injector extension? Stylus doesn't always work in my browser. I really like your theme and want to use it. Also, it'd be really helpful if you please modify the code as per the extension's requirements, as I don't really know CSS.

**Comment by arv-anshul** [comment]
Okay, for that I need to see how to write CSS for **Opera GX Browser**.

**Comment by Rekiro** [comment]
How do I get that?  (I switched to Opera One, btw)

**Comment by arv-anshul** [comment]
So install **Stylus Extension** in that browser and apply my theme. Maybe **Stylus** works well in **Opera One** browser.

**Comment by arv-anshul** [comment]
Hey @Rekiro

Did you install the theme in your browser?

**Comment by Rekiro** [comment]
Yes. I used [Code Injector](https://addons.opera.com/en-gb/extensions/details/code-injecto) extension.
